server:
  port: 0

spring:
  application:
    name: employee-education-service

  cache:
    redis:
      cache-null-values: false
      time-to-live: 120000

  datasource:
    url: jdbc:mysql://localhost:3306/JCByBharath1
    username: root
    password: JCBharath@2023
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 120000


logging:
  name: c:\Courses\Java\Logs\sb-inclass-project-2.log

  logback:
    rollingpolicy:
      max-file-size: 50KB
  level:
    root: INFO

    com:
      sb:
        inclass:
          project:
            sbinclassproject2:
              service: DEBUG
    org:
      springframework:
        cache: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
   # instance: localhost
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10